// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllChampionMasteries(arg1) {
  return window['go']['app']['App']['GetAllChampionMasteries'](arg1);
}

export function GetChallengers(arg1) {
  return window['go']['app']['App']['GetChallengers'](arg1);
}

export function GetChampionMastery(arg1, arg2) {
  return window['go']['app']['App']['GetChampionMastery'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetGrandmasters(arg1) {
  return window['go']['app']['App']['GetGrandmasters'](arg1);
}

export function GetMasters(arg1) {
  return window['go']['app']['App']['GetMasters'](arg1);
}

export function GetRankedStats(arg1) {
  return window['go']['app']['App']['GetRankedStats'](arg1);
}

export function GetSummonerByID(arg1) {
  return window['go']['app']['App']['GetSummonerByID'](arg1);
}

export function GetSummonerByPUUID(arg1) {
  return window['go']['app']['App']['GetSummonerByPUUID'](arg1);
}

export function GetTotalMasteryScore(arg1) {
  return window['go']['app']['App']['GetTotalMasteryScore'](arg1);
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function IsConfigured() {
  return window['go']['app']['App']['IsConfigured']();
}

export function SearchSummoner(arg1) {
  return window['go']['app']['App']['SearchSummoner'](arg1);
}

export function SetAPIKey(arg1) {
  return window['go']['app']['App']['SetAPIKey'](arg1);
}

export function SetRegion(arg1) {
  return window['go']['app']['App']['SetRegion'](arg1);
}
