// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {lol} from '../models';
import {config} from '../models';
import {lcu} from '../models';
import {app} from '../models';

export function GetAllChampionMasteries(arg1:string):Promise<Array<lol.ChampionMasteryInfo>>;

export function GetChallengers(arg1:string):Promise<lol.LeagueListInfo>;

export function GetChampionMastery(arg1:string,arg2:string):Promise<lol.ChampionMasteryInfo>;

export function GetConfig():Promise<config.Config>;

export function GetCurrentSummoner():Promise<lcu.CurrentSummoner>;

export function GetGrandmasters(arg1:string):Promise<lol.LeagueListInfo>;

export function GetLCUStatus():Promise<app.LCUStatus>;

export function GetMasters(arg1:string):Promise<lol.LeagueListInfo>;

export function GetOwnedChampions():Promise<Array<lcu.Champion>>;

export function GetRankedStats(arg1:string):Promise<Array<lol.RankedInfo>>;

export function GetSummonerByID(arg1:string):Promise<lol.SummonerInfo>;

export function GetSummonerByPUUID(arg1:string):Promise<lol.SummonerInfo>;

export function GetTotalMasteryScore(arg1:string):Promise<number>;

export function IsConfigured():Promise<boolean>;

export function SearchSummoner(arg1:string):Promise<lol.SummonerInfo>;

export function SetAPIKey(arg1:string):Promise<void>;

export function SetRegion(arg1:string):Promise<void>;

export function StartAutoPick(arg1:app.AutoPickConfig):Promise<void>;

export function StopAutoPick():Promise<void>;

export function UpdateAutoPickConfig(arg1:app.AutoPickConfig):Promise<void>;
